// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActionCompleted(arg1) {
  return window['go']['wails']['AppAPI']['ActionCompleted'](arg1);
}

export function ActionFailed(arg1, arg2) {
  return window['go']['wails']['AppAPI']['ActionFailed'](arg1, arg2);
}

export function ActionProgress(arg1, arg2, arg3) {
  return window['go']['wails']['AppAPI']['ActionProgress'](arg1, arg2, arg3);
}

export function BuildActionPlan(arg1) {
  return window['go']['wails']['AppAPI']['BuildActionPlan'](arg1);
}

export function CancelScan(arg1) {
  return window['go']['wails']['AppAPI']['CancelScan'](arg1);
}

export function ClearThumbnailCache() {
  return window['go']['wails']['AppAPI']['ClearThumbnailCache']();
}

export function ExecuteActionPlan(arg1) {
  return window['go']['wails']['AppAPI']['ExecuteActionPlan'](arg1);
}

export function ExportScanReport(arg1, arg2) {
  return window['go']['wails']['AppAPI']['ExportScanReport'](arg1, arg2);
}

export function GetCategoryFiles(arg1) {
  return window['go']['wails']['AppAPI']['GetCategoryFiles'](arg1);
}

export function GetDuplicateGroup(arg1) {
  return window['go']['wails']['AppAPI']['GetDuplicateGroup'](arg1);
}

export function GetImagePreview(arg1) {
  return window['go']['wails']['AppAPI']['GetImagePreview'](arg1);
}

export function GetScanSession(arg1) {
  return window['go']['wails']['AppAPI']['GetScanSession'](arg1);
}

export function GetScanSummary(arg1) {
  return window['go']['wails']['AppAPI']['GetScanSummary'](arg1);
}

export function GetSettings() {
  return window['go']['wails']['AppAPI']['GetSettings']();
}

export function ListActionHistory(arg1) {
  return window['go']['wails']['AppAPI']['ListActionHistory'](arg1);
}

export function ListCategories(arg1) {
  return window['go']['wails']['AppAPI']['ListCategories'](arg1);
}

export function ListDuplicateGroups(arg1) {
  return window['go']['wails']['AppAPI']['ListDuplicateGroups'](arg1);
}

export function ListLargeFiles(arg1) {
  return window['go']['wails']['AppAPI']['ListLargeFiles'](arg1);
}

export function ListScanSessions() {
  return window['go']['wails']['AppAPI']['ListScanSessions']();
}

export function OpenFile(arg1) {
  return window['go']['wails']['AppAPI']['OpenFile'](arg1);
}

export function RevealInFileManager(arg1) {
  return window['go']['wails']['AppAPI']['RevealInFileManager'](arg1);
}

export function ScanCancelled(arg1) {
  return window['go']['wails']['AppAPI']['ScanCancelled'](arg1);
}

export function ScanCompleted(arg1) {
  return window['go']['wails']['AppAPI']['ScanCompleted'](arg1);
}

export function ScanFailed(arg1, arg2) {
  return window['go']['wails']['AppAPI']['ScanFailed'](arg1, arg2);
}

export function ScanProgress(arg1) {
  return window['go']['wails']['AppAPI']['ScanProgress'](arg1);
}

export function SelectFolders() {
  return window['go']['wails']['AppAPI']['SelectFolders']();
}

export function StartScan(arg1) {
  return window['go']['wails']['AppAPI']['StartScan'](arg1);
}

export function UndoAction(arg1) {
  return window['go']['wails']['AppAPI']['UndoAction'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['wails']['AppAPI']['UpdateSettings'](arg1);
}
