// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {actions} from '../models';
import {duplicates} from '../models';
import {scan} from '../models';
import {settings} from '../models';
import {events} from '../models';

export function ActionCompleted(arg1:string):Promise<void>;

export function ActionFailed(arg1:string,arg2:string):Promise<void>;

export function ActionProgress(arg1:string,arg2:number,arg3:number):Promise<void>;

export function BuildActionPlan(arg1:dto.BuildActionPlanRequest):Promise<actions.Action>;

export function CancelScan(arg1:string):Promise<void>;

export function ClearThumbnailCache():Promise<void>;

export function ExecuteActionPlan(arg1:dto.BuildActionPlanRequest):Promise<actions.Action>;

export function ExportScanReport(arg1:string,arg2:string):Promise<dto.ExportResultDto>;

export function GetCategoryFiles(arg1:dto.PageQuery):Promise<dto.PaginatedFilesDto>;

export function GetDuplicateGroup(arg1:string):Promise<duplicates.Group>;

export function GetImagePreview(arg1:string):Promise<string>;

export function GetScanSession(arg1:string):Promise<scan.Session>;

export function GetScanSummary(arg1:string):Promise<scan.Session>;

export function GetSettings():Promise<settings.Settings>;

export function ListActionHistory(arg1:dto.PageQuery):Promise<Array<actions.Action>>;

export function ListCategories(arg1:string):Promise<Array<Record<string, any>>>;

export function ListDuplicateGroups(arg1:dto.PageQuery):Promise<dto.PaginatedDuplicateGroupsDto>;

export function ListLargeFiles(arg1:dto.PageQuery):Promise<dto.PaginatedFilesDto>;

export function ListScanSessions():Promise<Array<scan.Session>>;

export function OpenFile(arg1:string):Promise<void>;

export function RevealInFileManager(arg1:string):Promise<void>;

export function ScanCancelled(arg1:string):Promise<void>;

export function ScanCompleted(arg1:string):Promise<void>;

export function ScanFailed(arg1:string,arg2:string):Promise<void>;

export function ScanProgress(arg1:events.ScanProgress):Promise<void>;

export function SelectFolders():Promise<dto.FolderSelectionResult>;

export function StartScan(arg1:dto.StartScanRequest):Promise<scan.Session>;

export function UndoAction(arg1:string):Promise<actions.Action>;

export function UpdateSettings(arg1:settings.Settings):Promise<settings.Settings>;
